easy_admin:
    entities:
        Products:
            class: '%mtt_catalog.product_entity%'
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - name
                    - sku
                    - idErp
                    - { property: 'type', type_options: { disabled: true }  }
                    - active
                    - { property: 'mainImageFile', type: 'vich_image' }
                    - { property: 'description', type: 'ckeditor' }
                    - price
                    - parent
                    - categories
                    - { property: 'createdAt',  type_options: { disabled: true } }
                    - slug
                    - onSite
                    - seoH1
                    - seoTitle
            list:
                fields: ['id', 'sku', 'idErp', 'type', { property: 'mainImage', template: '@catalog_templates\easy_admin\vich_uploader_image.html.twig', base_path: '%mtt_catalog.image_path_to_product%' }, 'name', 'active', 'price']
        Categories:
            class: '%mtt_catalog.category_entity%'