easy_admin:
    entities:
        Products:
            class: '%mtt_catalog.product_entity%'
            form:
                fields:
                    - name
                    - sku
                    - idErp
                    - { property: 'type', type_options: { disabled: true }  }
                    - active
                    - { property: 'mainImageFile', type: 'vich_image' }
                    - { property: 'description', type: 'ckeditor' }
                    - price
                    - parent
                    - categories
                    - { property: 'createdAt',  type_options: { disabled: true } }
                    - slug
                    - onSite
                    - seoH1
                    - seoTitle
                    - characteristicsValues
            list:
                fields: ['id', 'sku', 'idErp', 'type', { property: 'mainImage', template: '@catalog_templates\easy_admin\vich_uploader_image.html.twig', base_path: '%mtt_catalog.image_path_to_product%' }, 'name', 'active', 'price']
        Categories:
            class: '%mtt_catalog.category_entity%'
            list:
                fields: ['id', 'slug', 'idErp', 'name', 'parent']
            form:
                fields:
                    - idErp
                    - name
                    - { property: 'mainImageFile', type: 'vich_image' }
                    - { property: 'descriptionShort', type: 'ckeditor' }
                    - { property: 'description', type: 'ckeditor' }
                    - slug
                    - template
                    - parent
                    - seoTitle
                    - seoH1
            list:
                fields: ['id', 'name', 'slug', 'active']
        Characteristics:
            class: '%mtt_catalog.characteristic_entity%'
            list:
                fields: ['id', 'name', 'slug', 'active']
            form:
                fields:
                    - name
                    - active
                    - onSearch
                    - onIndex
                    - isVisible
                    - slug
                    - valuesCollection
        CharacteristicValues:
            class: '%mtt_catalog.characteristic_value_entity%'
            list:
                fields: ['id', 'name', 'slug']