catalog:
    path:  /catalog
    defaults: { _controller: "MttCatalogBundle:Product:index" }

catalog_category:
    path:  /catalog/category/{slug}
    defaults: { _controller: "MttCatalogBundle:Category:index" }

catalog_show:
    path:  /catalog/product/{slug}
    defaults: { _controller: "MttCatalogBundle:Product:show" }
    
